baseURL = "https://fdgggy.github.io/"
languageCode = "zh-CN"
title = "niep的博客"
theme = "maupassant"
## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true
# 默认是70
hasCJKLanguage = true
summaryLength = 140

[author]
  name = "niep"

[params]
  author = "niep"
  subtitle = "专注于golang、skynet、unity3d、linux、移动互联网、项目管理、软件架构"
  keywords = "golang,go语言笔记,niep,博客,软件架构,skynet,unity3d,linux"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、项目管理、软件架构等"
  busuanzi = true

[params.utteranc]
    enable = true
    repo = "fdgggy/fdgggy.github.io"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[menu]
  # [[menu.main]]
  #   identifier = "books"
  #   name = "新书"
  #   url = "/books/"
  #   weight = 2
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4


googleAnalytics = "GA ID"
